Fix/vlwa-1116 defect tapping swap doesnt lead to swap menu null div error
velas/mobile-wallet pull request #109
Opened 2022-01-14 15:21 UTC by FrozenPyrozen

## Description

Fixed opening of swap screen for busd on testnet.

- separated `getHomeFeeWithAvaliableWeb3Provider` from `getBridgeInfo`
- make `contract` with available provider recursively in `getHomeFeeWithAvaliableWeb3Provider`
- changed provider if it's slow on getBridgeInfo

[vlwa-1116](https://velasnetwork.atlassian.net/browse/vlwa-1116) – [defect] tapping swap doesn't lead to swap menu, null div error

2022-01-14 15:51 UTC, kemston approved these changes

2022-01-16 10:27 UTC, Apindes requested changes

2022-01-16 10:27 UTC, Apindes commented on wallet/contracts.js
> +const getHomeFeeWithAvaliableWeb3Provider = ({
I suggest that function  getHomeFeeWithAvaliableWeb3Providershould returns only home fee

2022-01-17 13:43 UTC, Apindes approved these changes

2022-01-18 11:39 UTC, Corresponsible approved these changes

2022-01-18 11:40 UTC, merged