Large tx size VLWA-1499
velas/mobile-wallet pull request #187
Opened 2022-04-21 08:47 UTC by Apindes

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

2022-04-21 09:17 UTC, FrozenPyrozen approved these changes

2022-05-10 14:00 UTC, davinctor commented on pages/ConfirmExitValidator.js
> +            'Error',
The same about title

2022-05-10 14:01 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +import BN from 'bn.js';
Move libraries imports to the top please

2022-05-10 14:07 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +      if (err) {
Prefer to reduce the code tree
```
if (!err) {
      changePage('detailsValidator')();
      store.amountWithdraw = null;
}
// etc
````

2022-05-10 14:10 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +  //const signatures = ["5L8CQNFAJXvf3FboLebCtq4sNu67jugca6HkFejAUwU4r84vAqaJvaG7jqssATezfxapt6dQrkJopuYNpDaNoJ18", "512wGX82LKyb2wjZLXGwFD2CHbNjZqG6ToZf2qxadArdHnxWeRncN6vPCzJMTfNJ5UjCmHfD8sYWFKh33S
Drop if not used

2022-05-10 14:11 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +        smallTitle={lang.exitValidator.length > 15 ? true : false}
just `lang.exitValidator.length > 15`

2022-05-10 14:14 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +                        console.log({ err, info });
Drop logs please

2022-05-10 14:15 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +                            'Error',
Translations please

2022-05-10 14:16 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +                    Alert.alert('Error', errMsg);
Use translations please

2022-05-10 14:17 UTC, davinctor commented on pages/ConfirmExtraExitValidator.js
> +    // justifyContent: "space-between",
Drop used styles

2022-05-10 14:18 UTC, davinctor commented on pages/ConfirmStake.js
> +          Alert.alert('Error', err);
Translations for title

2022-05-10 14:18 UTC, davinctor commented on pages/ConfirmStake.js
>          }, 1000);
What's the purpose for timeout value?

2022-05-10 14:19 UTC, davinctor commented on pages/ExitValidator.js
> +        return Alert.alert('Error', errMessage);
Translations for title

2022-05-10 14:24 UTC, davinctor commented on staking/staking-store.js
> +          !unixTimestamp || new BN(unixTimestamp).lt(new BN(Date.now() / 1000))
Please create a separate boolean variable for this value with good name to increase readability =)

2022-05-10 14:26 UTC, davinctor commented on staking/staking-store.js
> +    if (this.txsProgress.filter((it) => it.transaction).length > 1)
please create separate boolean variable to increase code readability

2022-05-10 14:28 UTC, davinctor commented on staking/staking-store.js
> +      await new Promise((resolve) => setTimeout(resolve, 2000));
Move please to util function, like sleep (or any similar name)

2022-05-10 14:29 UTC, davinctor commented on staking/staking-store.js
> +      if (Date.now() > start + 60000) {
create please separate boolean variable to increase readability of this statement

2022-05-10 14:29 UTC, davinctor commented on staking/staking-store.js
> +          'Transaction checkTxConfirmation timeout has expired. Try to repeat later.'
What do you if wrap aslo with Error? Like `new Error('Transaction checkTxConfirmation timeout has expired. Try to repeat later.')`

2022-05-10 14:30 UTC, davinctor commented on staking/staking-store.js
> +        if (
Should in else be `cb(err)`?

2022-05-10 14:31 UTC, davinctor commented on staking/staking-store.js
> +      1000
Move to constants, please

2022-05-10 14:35 UTC, davinctor commented on staking/staking-store.js
> +      const account = filteredAccounts[i];
this could be refactored to chained calls like `filteredAccounts.map().forEach()` if you like, just suggestion

2022-05-10 14:35 UTC, davinctor commented on staking/staking-store.js
> +      await new Promise((resolve) => setTimeout(resolve, 2000));
Use util sleep function

2022-05-10 14:36 UTC, davinctor commented on utils/errorParser.js
> +    const result =
`(result || '').toString().indexOf()` might be moved to separate helper private function (or even inner)

2022-05-10 14:37 UTC, davinctor requested changes
Check my comments please

2022-05-10 14:48 UTC, Apindes commented on pages/ConfirmExtraExitValidator.js
> +import BN from 'bn.js';
done

2022-05-10 14:49 UTC, Apindes commented on pages/ConfirmExtraExitValidator.js
> +            'Error',
in the next iteration

2022-05-11 08:30 UTC, Apindes commented on pages/ConfirmExtraExitValidator.js
> +      if (err) {
no idea how to reduce this piece of code)

2022-05-11 08:34 UTC, Apindes commented on staking/staking-store.js
> +          'Transaction checkTxConfirmation timeout has expired. Try to repeat later.'
No need because errors are always passed in callback as 1-st argument

2022-05-11 08:37 UTC, Apindes commented on staking/staking-store.js
> +        if (
There is 2 options where we pass error in callback:

2022-05-11 08:43 UTC, Apindes commented on staking/staking-store.js
> +      if (!inactive || (state !== 'inactive' && state !== 'deactivating')) {
**getStakeActivation** method returns predefined constants. No need to create duplicates for them.

2022-05-11 09:57 UTC, Apindes commented on staking/staking-store.js
> +      const account = filteredAccounts[i];
for async functions inside loop classic for-each is better

2022-05-11 11:51 UTC, davinctor commented on staking/staking-store.js
> +      sleep(2000);
Looks like await is missed

2022-05-11 11:52 UTC, davinctor commented on staking/staking-store.js
> +      sleep(2000);
Looks like await is missed

2022-05-11 11:52 UTC, davinctor commented on staking/staking-store.js
> +      sleep(2000);
Looks like await is missed

2022-05-11 11:52 UTC, davinctor approved these changes

2022-05-23 10:13 UTC, Apindes commented on staking/staking-store.js
> +      sleep(2000);
fixed

2022-05-23 10:14 UTC, Apindes commented on staking/staking-store.js
> +      sleep(2000);
fixed

2022-05-23 10:17 UTC, FrozenPyrozen approved these changes

2022-05-25 10:41 UTC, Corresponsible approved these changes

2022-05-25 10:41 UTC, merged