VLWA-1767 add test IDs
velas/mobile-wallet pull request #223
Opened 2022-06-29 13:32 UTC by Corresponsible

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

[VLWA-1767](https://velasnetwork.atlassian.net/browse/VLWA-1767) – add test IDs

2022-07-01 11:57 UTC, olexandr13 requested changes

2022-07-01 11:57 UTC, olexandr13 commented on components/ButtonBlock.js
> +  const checkType = (type) => {
```
  const checkType = (type) => {
    return (
      {
        STAKE_MORE: 'stakeMoreButtonOnDetails',
        STAKE: 'stakeButtonOnDetails',
        OK: 'okButtonOnStakingSuccess',
        NEXT: 'nextButtonOnStake',
        CONFIRM: 'confirmButtonOnStake',
        REQUEST_WITHDRAW: 'requestWithdrawButtonOnDetails',
        WITHDRAW: 'withdrawButtonOnExitStake',
        DISABLED: 'disabledButtonOnStake',
      }[type] || null
    );
  };
```

2022-07-01 11:57 UTC, olexandr13 commented on components/DetailsValidatorComponent.js
> +                return index == 0 ? word.toLowerCase() : word.toUpperCase();
в чем логика именно этой строчки?

2022-07-01 11:57 UTC, olexandr13 commented on components/DetailsValidatorComponent.js
> +              .replace(/\s+/g, '')}`}
и этой

2022-07-01 16:18 UTC, Apindes approved these changes

2022-07-01 16:30 UTC, FrozenPyrozen approved these changes

2022-07-04 10:46 UTC, olexandr13 approved these changes

2022-07-04 10:53 UTC, merged