Feature/swap tokens
velas/mobile-wallet pull request #69
Opened 2021-12-07 14:11 UTC by Apindes

2021-12-07 15:04 UTC, Apindes commented
@Corresponsible fixed https://velasnetwork.atlassian.net/browse/VLWA-808 here

2021-12-09 18:48 UTC, kemston approved these changes

2021-12-09 19:39 UTC, FrozenPyrozen requested changes

2021-12-09 19:39 UTC, FrozenPyrozen commented on components/walletUserHistoryDetail.js
> +						onPress={() => {Linking.openURL(txurl)}}
Can we separate `() => {Linking.openURL(txurl)}` into function like `const openTxUrl = () => Linking.openURL(txurl)` to reuse it here and on line 153?

2021-12-09 19:39 UTC, FrozenPyrozen commented on components/BridgeDetailsModal.js
> +	const title = "Swap from " + fromNetwork + " to " + toNetwork;
Can be replaced with template string ``Swap from ${fromNetwork} to ${toNetwork}`

2021-12-09 23:29 UTC, Apindes commented on Styles.js
> +				backgroundColor: "transparent",
Sure. We will dive into it in the next release

2021-12-10 09:53 UTC, FrozenPyrozen requested changes

2021-12-10 09:53 UTC, FrozenPyrozen commented on App-ready.js
> +import Confirm2 from './components/Confirm2.js';
If there are some difference between them we can name like `ConfirmWithDifferences`

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/BridgeDetailsModal.js
> +  const MAX_LIMIT = ">100,000,000"
We can separate it above the component to not initial this value every time when it rerenders for example on line 8 , because it's constant value

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/SectionList.js
> +		}
Great job💪

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/SectionList.js
> +	container: {
Do we really need `container` with comented styles?

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/SectionList.js
> +});
Add newline please 
![image](https://user-images.githubusercontent.com/38257513/145553652-56a78da2-9926-4a27-94b2-5f5a9b38c429.png)

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/WalletItem.js
> +		if ((props.name).toLowerCase().indexOf('legacy') === -1) return null;
Can we separate it to variable like `const isNotLegacy = (props.name).toLowerCase().indexOf('legacy') === -1;`?

2021-12-10 09:53 UTC, FrozenPyrozen commented on components/WalletItem.js
> +						{ color: props.active ?  "#fff" : "#fff" },
Do we need this statement `color: props.active ?  "#fff" : "#fff"`? Because no difference here it will be the `"#fff` anywhay)

2021-12-10 09:53 UTC, FrozenPyrozen commented on pages/Wallet.js
> +			const r_amount = roundNumber(balance, {decimals: 6});
Well done)

2021-12-10 09:53 UTC, FrozenPyrozen commented on web3t/providers/velas_erc20.js
> +    web3 = getWeb3(network);
Noice)

2021-12-10 10:03 UTC, kemston submitted a review, later dismissed

2021-12-10 13:22 UTC, FrozenPyrozen requested changes

2021-12-10 13:22 UTC, FrozenPyrozen commented on components/WalletItem.js
> +		if (isNotLegacy) return null;
Noice

2021-12-10 13:22 UTC, FrozenPyrozen commented on components/WalletItem.js
> +  	switch (true) {
Maybe place `wallet.coin.token` instead of `true` here and left `case 'vlx2'` on line 61 for better readability

2021-12-10 13:22 UTC, FrozenPyrozen commented on pages/Withdraw.js
> +	if (!wallet.coin[network]) {
Can unite `!wallet.coin[network]` with` !wallet` from line 52 to `if(!wallet && !wallet.coin[network]) {
return null;
}`

2021-12-13 16:04 UTC, kemston submitted a review, later dismissed

2021-12-21 13:42 UTC, kemston submitted a review, later dismissed

2021-12-22 09:20 UTC, Apindes commented on components/BridgeDetailsModal.js
> +	const fromNetwork = (name != null ? name : "").toUpperCase();
Don`t need strict check, cause it check if it is not null and not undefined.

2021-12-22 09:33 UTC, FrozenPyrozen approved these changes

2021-12-22 13:29 UTC, FrozenPyrozen commented on pages/Withdraw.js
> +                          { width: '100%', fontSize: 18, borderBottomWidth: 1 },
Added `borderBottomWidth: 1` here

2021-12-24 09:14 UTC, FrozenPyrozen submitted a review, later dismissed

2022-01-09 00:49 UTC, Apindess commented on components/WalletItem.js
> +		if ((props.name).toLowerCase().indexOf('legacy') === -1) return null;
This will be removed later

2022-01-09 00:54 UTC, Apindess approved these changes

2022-01-09 00:54 UTC, Apindess commented on App-ready.js
> +import ConfirmDetailed from './components/Confirm2.js';
ready

2022-01-09 00:55 UTC, Apindess commented on components/WalletItem.js
> +  	switch (true) {
done

2022-01-13 15:28 UTC, FrozenPyrozen approved these changes

2022-01-14 11:00 UTC, Corresponsible approved these changes

2022-01-14 11:03 UTC, merged