Bugfix staking
velas/mobile-wallet pull request #75
Opened 2021-12-13 14:52 UTC by dmitrii602

# [VLWA-981](https://velasnetwork.atlassian.net/browse/VLWA-NUMBER_HERE)

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Step 1
- [ ] Step 2

### Platforms tested on

- [ ] Android
- [ ] IOS

### Image(s) showcasing change, if possible

2021-12-14 09:47 UTC, FrozenPyrozen requested changes

2021-12-14 09:47 UTC, FrozenPyrozen commented on components/TabsBarValidator.js
> +          const DURATION = 1000 / 10;
Maybe separate `const DURATION = 1000 / 10;` into upper level?

2021-12-14 09:47 UTC, FrozenPyrozen commented on web3t/providers/insight.js
> +}).call(this);
Not critical, but recomended)
![image](https://user-images.githubusercontent.com/38257513/145973676-55788a11-37e5-4e1a-aec9-a932b1d71d35.png)

2021-12-14 14:13 UTC, dmitrii602 commented on components/ButtonBlock.js
> +    netInfo.isConnected === true ||
done

2021-12-14 14:13 UTC, dmitrii602 commented on components/TabsBarValidator.js
> +          const DURATION = 1000 / 10;
done

2021-12-14 14:13 UTC, dmitrii602 commented on web3t/providers/insight.js
> +}).call(this);
done

2021-12-22 09:06 UTC, FrozenPyrozen submitted a review, later dismissed

2021-12-23 10:05 UTC, FrozenPyrozen requested changes

2021-12-23 10:05 UTC, FrozenPyrozen commented on components/ButtonBlock.js
> +      case 'WITHDRAW':
We can use 
```
case 'REQUEST_WITHDRAW':
case 'WITHDRAW':
           return { color: '#fff' };
```

2021-12-23 10:06 UTC, FrozenPyrozen approved these changes

2021-12-24 09:15 UTC, FrozenPyrozen approved these changes

2022-01-04 13:23 UTC, Corresponsible approved these changes

2022-01-04 13:25 UTC, merged