feature/VLWA-1036: handle rpc error in sends\swaps
velas/mobile-wallet pull request #99
Opened 2022-01-06 17:07 UTC by kemston

…r message

# [Task name](https://velasnetwork.atlassian.net/browse/VLWA-NUMBER_HERE)

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Step 1
- [ ] Step 2

### Platforms tested on

- [ ] Android
- [ ] IOS

### Image(s) showcasing change, if possible

2022-01-06 17:17 UTC, Corresponsible approved these changes

2022-01-06 17:19 UTC, FrozenPyrozen approved these changes

2022-01-10 13:49 UTC, FrozenPyrozen submitted a review, later dismissed

2022-01-10 17:09 UTC, FrozenPyrozen approved these changes

2022-01-11 12:22 UTC, FrozenPyrozen requested changes

2022-01-11 12:22 UTC, FrozenPyrozen commented on components/errorParse.js
> +        onPress={() => Linking.openURL(error.hyperLink)}
Can we separate into `const openHyperlink = () => Linking.openURL(error.hyperLink)`

2022-01-11 12:22 UTC, FrozenPyrozen commented on components/errorParse.js
> +export default ({ error }) => (
Cam we destructure `{ text1, text2, hyperLink, textLink}` here?

2022-01-12 13:07 UTC, FrozenPyrozen approved these changes

2022-01-12 13:21 UTC, Corresponsible approved these changes

2022-01-12 13:21 UTC, merged